name: JLG21
version: '1.0.0'
main: de.martin.jumpleaguegym.main.Main
api-version: '1.21'

commands:
  hub:
    description: Teleportiert dich zurueck in die Lobby.
    aliases: l
  lobby:
    description: Teleportiert dich zur Lobby.
  modul:
    description: Teleportiert dich zu einem Modul.
  start:
    description: Startet die Jump-League Runde.
  practise:
    description: Practise-Modus fuer Module.
  items:
    description: Legt die Items in den Truhen fest.
  create:
    description: Erstellt das Jump and Run.
  resetjumpleague:
    description: Setzt das Jump and Run zurück.
  map:
    description: Erstellt/Löscht Deathmatch-Maps.
  mapLocation:
    description: Speichert Deatchmatch Spawnpoints, bounds und Endpoints.
  tpmapLocation:
    description: Tp't zu Deatchmatch Spawnpoints, bounds und Endpoints.
